### PR TITLE
Type specific visualization

### PR DESCRIPTION
**Pull request by JinkiJung**
- Type specific visualization
- X509 cert attribute visualization
- OCSP request/response visualization

### CODE REVIEW

**Review by oliverhaagh — APPROVED** [review]
I made a few small changes, but apart from that it looks good! 👍

**Comment by oliverhaagh** [comment]
Swagger does not work for some reason though, but I will try to fix that separately

**Comment by JinkiJung** [comment]
> I made a few small changes, but apart from that it looks good! 👍

Thank you very much for your commit and feedback! :0)

**Comment by JinkiJung** [comment]
> Swagger does not work for some reason though, but I will try to fix that separately

Noted. So it's time to go.

**Pull request merged**
